// Alert types
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// Toast types
export const SET_TOAST = 'SET_TOAST';
export const REMOVE_TOAST = 'REMOVE_TOAST';

// Registration types
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

// Authentication types
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

// Login types
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

// Profile types
export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED ';
export const USER_PROFILE_ERROR = 'USER_PROFILE_ERROR';

export const UPDATE_USER_PASSWORD = 'UPDATE_USER_PASSWORD';
export const UPDATE_USER_PASSWORD_ERROR = 'UPDATE_USER_PASSWORD_ERROR';

// Request Types
export const GET_ALL_REQUESTS = 'GET_ALL_REQUESTS';
export const GET_ALL_USER_REQUESTS = 'GET_ALL_USER_REQUESTS';
export const GET_A_SINGLE_REQUEST = 'GET_A_SINGLE_REQUEST';
export const REQUESTS_ERROR = 'REQUESTS_ERROR';

export const CREATE_A_REQUEST_SUCCESS = 'CREATE_A_REQUEST_SUCCESS';
export const CREATE_REQUEST_FAIL = 'CREATE_REQUEST_FAIL';

export const UPDATE_A_REQUEST_SUCCESS = 'UPDATE_A_REQUEST_SUCCESS';
export const UPDATE_REQUEST_STATUS_SUCCESS = 'UPDATE_REQUEST_STATUS_SUCCESS';
export const UPDATE_REQUEST_FAIL = 'UPDATE_REQUEST_FAIL';

export const DELETE_A_REQUEST = 'DELETE_A_REQUEST';
